name: proshop

services:
  api:
    build:
         
         dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    networks:
          - mern-app
    ports:
         - 8000:8000     
  frontend:
      build:
         context: ./frontend
         dockerfile: Dockerfile
      restart: unless-stopped
      volumes:
          - ./frontend:/app
          - /app/node_modules
      networks:
           - mern-app
      ports:
         - 3000:3000
      depends_on:     
           - api


networks:
 mern-app:
   driver: bridge           